$style:
- verbatim: |-
    \usepackage{math-common}
    \usepackage[utf8]{inputenc}
    \usepackage[T2A]{fontenc}
    \usepackage[russian]{babel}
    \usepackage[margin=2em]{geometry}
$build$matter:
- - .[no-header]
$matter:
- team
- pers
